In [1]:
pip install numpy

     -------------------------------------- 14.8/14.8 MB 611.5 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

Array dalam Numpy

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(a[0])

[1 2 3 4]


Creating Array

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
print(np.arange(4))

[0 1 2 3]


In [15]:
print(np.arange(0,10,2)) # (start, stop, step)

[0 2 4 6 8]


In [16]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

Add, Remove, and Sort

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Shape and Size

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [32]:
arr_one.ndim

2

In [33]:
arr_one.size

5

In [34]:
arr_one.shape

(1, 5)

Reshape

In [35]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [36]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [37]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

Convert 1D to 2D

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [41]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [46]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [44]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and Slicing

In [49]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [52]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [53]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [54]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [55]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [58]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [61]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [64]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [65]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations

In [69]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [70]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [71]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [72]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [73]:
data = np.array([1, 2])
data

array([1, 2])

In [74]:
ones = np.ones(2)
ones

array([1., 1.])

In [77]:
data + ones

array([2., 3.])

In [78]:
data * data

array([1, 4])

In [79]:
data / data

array([1., 1.])

Broadcasting

In [80]:
data * 2

array([2, 4])

More Array Operations

In [81]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [82]:
A.sum()

4.8595784

In [83]:
A.min()

0.05093587

In [84]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [85]:
A.max()

0.82485143

In [86]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [87]:
A.std()

0.21392120766089617

In [91]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.77395511 0.90167244]
 [0.95906248 0.07171379]
 [0.67310682 0.65511711]]


Matrix Arithmetic

In [92]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [93]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [94]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [95]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [96]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


Dot Product

In [97]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [98]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [100]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [101]:
print(data[0])
print(data[1])
print(data[2])

[1 2]
[3 4]
[5 6]


In [102]:
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

2
[[3 4]
 [5 6]]
[2 4]


Matrix Aggregation

In [103]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [104]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [105]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


Transposing and Reshaping

In [106]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [107]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [108]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [109]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


N-Dimensional Array

In [113]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [114]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [115]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [116]:
print(np.random.random((4,3,2)))

[[[0.06267909 0.98840065]
  [0.5451544  0.14195881]
  [0.58388574 0.97355317]]

 [[0.93194335 0.55446033]
  [0.19994395 0.38766137]
  [0.89128178 0.87269468]]

 [[0.28175048 0.31559425]
  [0.39293102 0.19427127]
  [0.24455484 0.42248619]]

 [[0.59921582 0.245397  ]
  [0.78998955 0.45803641]
  [0.29689804 0.83252224]]]


Flatten N-Dimensional Array

In [117]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])